config/routes.rb
Rails.application.routes.draw do

  get 'tasks', to: 'tasks#index', as: :tasks

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update'

  get 'tasks/:id', to: 'tasks#show', as: :task

  delete 'tasks/:id', to: 'tasks#destroy'

  get 'completed/:id', to: 'tasks#mark_completed', as: :completed
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/task_controller.rb
# Task controller
class TaskController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :mark_completed]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit; end

  def update
    @task.update(task_params)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def mark_completed
    @task.completed = !@task.completed
    @task.update
  end

  # private from here
  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/controllers/tasks_controller.rb
# Task controller
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :mark_completed]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def mark_completed
    @task.completed = !@task.completed
    @task.save
    redirect_to tasks_path
  end

  # private from here
  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container jumbotron">
      <%= yield %>
    </div>
  </body>
</html>

app/views/task/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit your task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>All your tasks</h1>
<%= link_to 'Create new +', tasks_new_path, class: 'm-8' %>


<ul class="list-tasks">
  <% @tasks.each do |t| %>
    <li>
      <span class="yellow"><%= link_to t.title, task_path(t) %></span>

      <%= link_to completed_path(t) do  %>
      <div class="btn-group-toggle" data-toggle="buttons">
        <label class="btn btn-info">
          <input type="checkbox" checked autocomplete="off">Done? : <%= t.completed ? 'Yesss' : 'Nope'%>
        </label>
        </div>
        <% end %>

        <%= link_to 'Delete', task_path(t),
            method: :delete,
            data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'  %>
    </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Create your task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>


 <li class="task-info">
    <p><%= @task.details %></p>

  <!-- <%= link_to 'completed', completed_path(@task) %> -->

  <%= link_to completed_path(@task) do  %>
    <div class="btn-group-toggle mx-2" data-toggle="buttons">
        <label class="btn btn-info">
          <input type="checkbox" checked autocomplete="off">Done? : <%= @task.completed ? 'Yesss' : 'Nope'%>
        </label>
    </div>
  <% end %>


    <%= link_to 'Edit', task_edit_path(@task),
        method: :get, class: 'btn btn-warning'  %>
    <%= link_to 'Delete', task_path(@task),
        method: :delete,
        data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'  %>
  </li>
<br>
<br>
<%= link_to 'Home', tasks_path, class: 'btn btn-success' %>